const CATEGORIES = {
  gameplay: { label: 'Gameplay', icon: '🎮' },
  time: { label: 'Time & Speed', icon: '⏰' },
  combat: { label: 'Combat & Damage', icon: '⚔️' },
  player: { label: 'Player Stats', icon: '👤' },
  pal: { label: 'Pal Stats', icon: '🦎' },
  base: { label: 'Base & Guild', icon: '🏠' },
  pvp: { label: 'PvP', icon: '🗡️' },
  world: { label: 'World & Items', icon: '🌍' },
  server: { label: 'Server', icon: '🖥️' },
  advanced: { label: 'Advanced', icon: '🔧' },
};

const SETTINGS_SCHEMA = [
  // Gameplay
  { key: 'Difficulty', label: 'Difficulty', category: 'gameplay', type: 'select', options: ['None', 'Custom', 'Easy', 'Normal', 'Hard'], description: 'Server difficulty preset' },
  { key: 'RandomizerType', label: 'Randomizer Type', category: 'gameplay', type: 'select', options: ['None', 'Default'], description: 'Type of randomizer to use' },
  { key: 'RandomizerSeed', label: 'Randomizer Seed', category: 'gameplay', type: 'text', description: 'Seed string for the randomizer' },
  { key: 'bIsRandomizerPalLevelRandom', label: 'Randomize Pal Levels', category: 'gameplay', type: 'boolean', description: 'Whether to randomize Pal levels' },
  { key: 'ExpRate', label: 'EXP Rate', category: 'gameplay', type: 'number', step: 0.5, min: 0, description: 'Experience gain multiplier' },
  { key: 'WorkSpeedRate', label: 'Work Speed Rate', category: 'gameplay', type: 'number', step: 0.5, min: 0, description: 'Global work speed multiplier' },
  { key: 'DeathPenalty', label: 'Death Penalty', category: 'gameplay', type: 'select', options: ['None', 'Item', 'ItemAndEquipment', 'All'], description: 'What items are lost on death' },

  // Time
  { key: 'DayTimeSpeedRate', label: 'Day Time Speed Rate', category: 'time', type: 'number', step: 0.5, min: 0, description: 'Speed multiplier for day time' },
  { key: 'NightTimeSpeedRate', label: 'Night Time Speed Rate', category: 'time', type: 'number', step: 0.5, min: 0, description: 'Speed multiplier for night time' },
  { key: 'AutoSaveSpan', label: 'Auto Save Span', category: 'time', type: 'number', step: 1, min: 0, description: 'Interval between auto saves in minutes' },
  { key: 'PalEggDefaultHatchingTime', label: 'Egg Hatching Time', category: 'time', type: 'number', step: 1, min: 0, description: 'Time required to hatch massive eggs in hours' },

  // Combat
  { key: 'PalDamageRateAttack', label: 'Pal Attack Damage Rate', category: 'combat', type: 'number', step: 0.5, min: 0, description: 'Damage multiplier for Pal attacks' },
  { key: 'PalDamageRateDefense', label: 'Pal Defense Damage Rate', category: 'combat', type: 'number', step: 0.5, min: 0, description: 'Damage taken multiplier for Pals' },
  { key: 'PlayerDamageRateAttack', label: 'Player Attack Damage Rate', category: 'combat', type: 'number', step: 0.5, min: 0, description: 'Damage multiplier for Player attacks' },
  { key: 'PlayerDamageRateDefense', label: 'Player Defense Damage Rate', category: 'combat', type: 'number', step: 0.5, min: 0, description: 'Damage taken multiplier for Players' },
  { key: 'EquipmentDurabilityDamageRate', label: 'Equipment Durability Damage Rate', category: 'combat', type: 'number', step: 0.5, min: 0, description: 'Rate at which equipment loses durability' },

  // Player
  { key: 'PlayerStomachDecreaceRate', label: 'Player Stomach Decrease Rate', category: 'player', type: 'number', step: 0.5, min: 0, description: 'Rate at which player hunger decreases' },
  { key: 'PlayerStaminaDecreaceRate', label: 'Player Stamina Decrease Rate', category: 'player', type: 'number', step: 0.5, min: 0, description: 'Rate at which player stamina decreases' },
  { key: 'PlayerAutoHPRegeneRate', label: 'Player Auto HP Regen Rate', category: 'player', type: 'number', step: 0.5, min: 0, description: 'Rate at which player HP naturally regenerates' },
  { key: 'PlayerAutoHpRegeneRateInSleep', label: 'Player Sleep HP Regen Rate', category: 'player', type: 'number', step: 0.5, min: 0, description: 'Rate at which player HP regenerates while sleeping' },
  { key: 'ItemWeightRate', label: 'Item Weight Rate', category: 'player', type: 'number', step: 0.5, min: 0, description: 'Multiplier for item weight' },
  { key: 'bEnableAimAssistPad', label: 'Enable Aim Assist (Gamepad)', category: 'player', type: 'boolean', description: 'Enable aim assist for gamepad users' },
  { key: 'bEnableAimAssistKeyboard', label: 'Enable Aim Assist (Keyboard)', category: 'player', type: 'boolean', description: 'Enable aim assist for keyboard users' },
  { key: 'bAllowEnhanceStat_Health', label: 'Allow Enhance Health', category: 'player', type: 'boolean', description: 'Allow players to enhance their health stat' },
  { key: 'bAllowEnhanceStat_Attack', label: 'Allow Enhance Attack', category: 'player', type: 'boolean', description: 'Allow players to enhance their attack stat' },
  { key: 'bAllowEnhanceStat_Stamina', label: 'Allow Enhance Stamina', category: 'player', type: 'boolean', description: 'Allow players to enhance their stamina stat' },
  { key: 'bAllowEnhanceStat_Weight', label: 'Allow Enhance Weight', category: 'player', type: 'boolean', description: 'Allow players to enhance their weight stat' },
  { key: 'bAllowEnhanceStat_WorkSpeed', label: 'Allow Enhance Work Speed', category: 'player', type: 'boolean', description: 'Allow players to enhance their work speed stat' },

  // Pal
  { key: 'PalCaptureRate', label: 'Pal Capture Rate', category: 'pal', type: 'number', step: 0.5, min: 0, description: 'Multiplier for Pal capture chance' },
  { key: 'PalSpawnNumRate', label: 'Pal Spawn Num Rate', category: 'pal', type: 'number', step: 0.5, min: 0, description: 'Multiplier for the number of Pals that spawn' },
  { key: 'PalStomachDecreaceRate', label: 'Pal Stomach Decrease Rate', category: 'pal', type: 'number', step: 0.5, min: 0, description: 'Rate at which Pal hunger decreases' },
  { key: 'PalStaminaDecreaceRate', label: 'Pal Stamina Decrease Rate', category: 'pal', type: 'number', step: 0.5, min: 0, description: 'Rate at which Pal stamina decreases' },
  { key: 'PalAutoHPRegeneRate', label: 'Pal Auto HP Regen Rate', category: 'pal', type: 'number', step: 0.5, min: 0, description: 'Rate at which Pal HP naturally regenerates' },
  { key: 'PalAutoHpRegeneRateInSleep', label: 'Pal Sleep HP Regen Rate', category: 'pal', type: 'number', step: 0.5, min: 0, description: 'Rate at which Pal HP regenerates while sleeping' },
  { key: 'MonsterFarmActionSpeedRate', label: 'Monster Farm Action Speed Rate', category: 'pal', type: 'number', step: 0.5, min: 0, description: 'Speed multiplier for Pal actions in the farm' },
  { key: 'EnablePredatorBossPal', label: 'Enable Predator Boss Pal', category: 'pal', type: 'boolean', description: 'Whether predator boss Pals are enabled' },
  { key: 'bPalLost', label: 'Pal Lost', category: 'pal', type: 'boolean', description: 'Whether Pals can be permanently lost' },

  // Base
  { key: 'BaseCampMaxNum', label: 'Base Camp Max Num', category: 'base', type: 'number', step: 1, min: 0, description: 'Maximum number of base camps allowed per guild' },
  { key: 'BaseCampWorkerMaxNum', label: 'Base Camp Worker Max Num', category: 'base', type: 'number', step: 1, min: 0, description: 'Maximum number of Pals allowed to work at a base camp' },
  { key: 'BaseCampMaxNumInGuild', label: 'Base Camp Max Num In Guild', category: 'base', type: 'number', step: 1, min: 0, description: 'Maximum number of base camps a guild can have' },
  { key: 'GuildPlayerMaxNum', label: 'Guild Player Max Num', category: 'base', type: 'number', step: 1, min: 0, description: 'Maximum number of players allowed in a guild' },
  { key: 'bAutoResetGuildNoOnlinePlayers', label: 'Auto Reset Guild No Online Players', category: 'base', type: 'boolean', description: 'Automatically reset guilds with no online players' },
  { key: 'AutoResetGuildTimeNoOnlinePlayers', label: 'Auto Reset Guild Time No Online Players', category: 'base', type: 'number', step: 1, min: 0, description: 'Hours before a guild with no online players is reset' },
  { key: 'GuildRejoinCooldownMinutes', label: 'Guild Rejoin Cooldown Minutes', category: 'base', type: 'number', step: 1, min: 0, description: 'Cooldown in minutes before a player can rejoin a guild' },
  { key: 'AutoTransferMasterCheckIntervalSeconds', label: 'Auto Transfer Master Check Interval Seconds', category: 'base', type: 'number', step: 1, min: 0, description: 'Interval in seconds to check for auto-transferring guild master' },
  { key: 'AutoTransferMasterThresholdDays', label: 'Auto Transfer Master Threshold Days', category: 'base', type: 'number', step: 1, min: 0, description: 'Days offline before guild master is automatically transferred' },
  { key: 'MaxGuildsPerFrame', label: 'Max Guilds Per Frame', category: 'base', type: 'number', step: 1, min: 0, description: 'Maximum number of guilds processed per frame' },
  { key: 'BuildObjectHpRate', label: 'Build Object Hp Rate', category: 'base', type: 'number', step: 0.5, min: 0, description: 'Multiplier for built object health' },
  { key: 'BuildObjectDamageRate', label: 'Build Object Damage Rate', category: 'base', type: 'number', step: 0.5, min: 0, description: 'Damage multiplier against built objects' },
  { key: 'BuildObjectDeteriorationDamageRate', label: 'Build Object Deterioration Damage Rate', category: 'base', type: 'number', step: 0.5, min: 0, description: 'Rate at which built objects deteriorate outside of base' },
  { key: 'bBuildAreaLimit', label: 'Build Area Limit', category: 'base', type: 'boolean', description: 'Enable restrictions on where players can build' },
  { key: 'MaxBuildingLimitNum', label: 'Max Building Limit Num', category: 'base', type: 'number', step: 1, min: 0, description: 'Maximum number of buildings allowed' },
  { key: 'bEnableBuildingPlayerUIdDisplay', label: 'Enable Building Player UId Display', category: 'base', type: 'boolean', description: 'Show the UID of the player who built an object' },
  { key: 'BuildingNameDisplayCacheTTLSeconds', label: 'Building Name Display Cache TTL Seconds', category: 'base', type: 'number', step: 1, min: 0, description: 'Time-to-live for building name display cache in seconds' },

  // PvP
  { key: 'bIsPvP', label: 'Is PvP', category: 'pvp', type: 'boolean', description: 'Enable Player vs Player combat' },
  { key: 'bEnablePlayerToPlayerDamage', label: 'Enable Player To Player Damage', category: 'pvp', type: 'boolean', description: 'Allow players to damage each other' },
  { key: 'bEnableFriendlyFire', label: 'Enable Friendly Fire', category: 'pvp', type: 'boolean', description: 'Allow players to damage guild mates' },
  { key: 'bHardcore', label: 'Hardcore', category: 'pvp', type: 'boolean', description: 'Enable hardcore mode features' },
  { key: 'bCharacterRecreateInHardcore', label: 'Character Recreate In Hardcore', category: 'pvp', type: 'boolean', description: 'Allow character recreation in hardcore mode' },
  { key: 'bCanPickupOtherGuildDeathPenaltyDrop', label: 'Can Pickup Other Guild Death Penalty Drop', category: 'pvp', type: 'boolean', description: 'Allow picking up items dropped by other guild members on death' },
  { key: 'bEnableNonLoginPenalty', label: 'Enable Non Login Penalty', category: 'pvp', type: 'boolean', description: 'Enable penalties for not logging in' },
  { key: 'bExistPlayerAfterLogout', label: 'Exist Player After Logout', category: 'pvp', type: 'boolean', description: 'Keep player characters in the world after they log out' },
  { key: 'bEnableDefenseOtherGuildPlayer', label: 'Enable Defense Other Guild Player', category: 'pvp', type: 'boolean', description: 'Enable defenses against players from other guilds' },
  { key: 'bDisplayPvPItemNumOnWorldMap_BaseCamp', label: 'Display PvP Item Num On World Map Base Camp', category: 'pvp', type: 'boolean', description: 'Show PvP items at base camps on the map' },
  { key: 'bDisplayPvPItemNumOnWorldMap_Player', label: 'Display PvP Item Num On World Map Player', category: 'pvp', type: 'boolean', description: 'Show PvP items held by players on the map' },
  { key: 'AdditionalDropItemWhenPlayerKillingInPvPMode', label: 'Additional Drop Item When Player Killing In PvP Mode', category: 'pvp', type: 'text', description: 'Item ID to drop additionally when killing a player in PvP' },
  { key: 'AdditionalDropItemNumWhenPlayerKillingInPvPMode', label: 'Additional Drop Item Num When Player Killing In PvP Mode', category: 'pvp', type: 'number', step: 1, min: 0, description: 'Amount of additional item to drop when killing a player in PvP' },
  { key: 'bAdditionalDropItemWhenPlayerKillingInPvPMode', label: 'Additional Drop Item When Player Killing In PvP Mode', category: 'pvp', type: 'boolean', description: 'Enable additional item drops when killing players in PvP' },

  // World
  { key: 'CollectionDropRate', label: 'Collection Drop Rate', category: 'world', type: 'number', step: 0.5, min: 0, description: 'Multiplier for items gathered from collections' },
  { key: 'CollectionObjectHpRate', label: 'Collection Object Hp Rate', category: 'world', type: 'number', step: 0.5, min: 0, description: 'Multiplier for health of collectible objects' },
  { key: 'CollectionObjectRespawnSpeedRate', label: 'Collection Object Respawn Speed Rate', category: 'world', type: 'number', step: 0.5, min: 0, description: 'Multiplier for respawn speed of collectible objects' },
  { key: 'EnemyDropItemRate', label: 'Enemy Drop Item Rate', category: 'world', type: 'number', step: 0.5, min: 0, description: 'Multiplier for items dropped by defeated enemies' },
  { key: 'DropItemMaxNum', label: 'Drop Item Max Num', category: 'world', type: 'number', step: 1, min: 0, description: 'Maximum number of dropped items allowed in the world' },
  { key: 'PhysicsActiveDropItemMaxNum', label: 'Physics Active Drop Item Max Num', category: 'world', type: 'number', step: 1, min: 0, description: 'Maximum number of dropped items with active physics' },
  { key: 'DropItemMaxNum_UNKO', label: 'Drop Item Max Num UNKO', category: 'world', type: 'number', step: 1, min: 0, description: 'Maximum number of specific dropped items allowed' },
  { key: 'DropItemAliveMaxHours', label: 'Drop Item Alive Max Hours', category: 'world', type: 'number', step: 0.5, min: 0, description: 'Hours before dropped items despawn' },
  { key: 'bEnableInvaderEnemy', label: 'Enable Invader Enemy', category: 'world', type: 'boolean', description: 'Enable base raids by enemies' },
  { key: 'bActiveUNKO', label: 'Active UNKO', category: 'world', type: 'boolean', description: 'Enable specific active features' },
  { key: 'SupplyDropSpan', label: 'Supply Drop Span', category: 'world', type: 'number', step: 1, min: 0, description: 'Interval between supply drops in minutes' },
  { key: 'BlockRespawnTime', label: 'Block Respawn Time', category: 'world', type: 'number', step: 1, min: 0, description: 'Time it takes for blocks to respawn' },
  { key: 'RespawnPenaltyDurationThreshold', label: 'Respawn Penalty Duration Threshold', category: 'world', type: 'number', step: 1, min: 0, description: 'Threshold duration for respawn penalties' },
  { key: 'RespawnPenaltyTimeScale', label: 'Respawn Penalty Time Scale', category: 'world', type: 'number', step: 0.5, min: 0, description: 'Time scale for respawn penalties' },
  { key: 'ItemCorruptionMultiplier', label: 'Item Corruption Multiplier', category: 'world', type: 'number', step: 0.5, min: 0, description: 'Multiplier for item corruption or decay speed' },
  { key: 'bAllowGlobalPalboxExport', label: 'Allow Global Palbox Export', category: 'world', type: 'boolean', description: 'Allow exporting Pals to global Palbox' },
  { key: 'bAllowGlobalPalboxImport', label: 'Allow Global Palbox Import', category: 'world', type: 'boolean', description: 'Allow importing Pals from global Palbox' },
  { key: 'ItemContainerForceMarkDirtyInterval', label: 'Item Container Force Mark Dirty Interval', category: 'world', type: 'number', step: 1, min: 0, description: 'Interval for forcing item containers to mark as dirty' },
  { key: 'PlayerDataPalStorageUpdateCheckTickInterval', label: 'Player Data Pal Storage Update Check Tick Interval', category: 'world', type: 'number', step: 1, min: 0, description: 'Tick interval for checking player Pal storage updates' },

  // Server
  { key: 'ServerName', label: 'Server Name', category: 'server', type: 'text', description: 'Name of the server displayed in the browser' },
  { key: 'ServerDescription', label: 'Server Description', category: 'server', type: 'text', description: 'Description of the server displayed in the browser' },
  { key: 'AdminPassword', label: 'Admin Password', category: 'server', type: 'text', description: 'Password required for admin access' },
  { key: 'ServerPassword', label: 'Server Password', category: 'server', type: 'text', description: 'Password required to join the server' },
  { key: 'ServerPlayerMaxNum', label: 'Server Player Max Num', category: 'server', type: 'number', step: 1, min: 0, description: 'Maximum number of players allowed on the server' },
  { key: 'CoopPlayerMaxNum', label: 'Coop Player Max Num', category: 'server', type: 'number', step: 1, min: 0, description: 'Maximum number of players allowed in a co-op session' },
  { key: 'bIsMultiplay', label: 'Is Multiplay', category: 'server', type: 'boolean', description: 'Whether multiplayer is enabled' },
  { key: 'PublicPort', label: 'Public Port', category: 'server', type: 'number', step: 1, min: 0, description: 'The public port the server listens on' },
  { key: 'PublicIP', label: 'Public IP', category: 'server', type: 'text', description: 'The public IP address of the server' },
  { key: 'Region', label: 'Region', category: 'server', type: 'text', description: 'The geographical region of the server' },
  { key: 'bUseAuth', label: 'Use Auth', category: 'server', type: 'boolean', description: 'Whether to use authentication' },
  { key: 'bShowPlayerList', label: 'Show Player List', category: 'server', type: 'boolean', description: 'Whether the player list is visible' },
  { key: 'bIsShowJoinLeftMessage', label: 'Is Show Join Left Message', category: 'server', type: 'boolean', description: 'Show messages when players join or leave' },
  { key: 'ChatPostLimitPerMinute', label: 'Chat Post Limit Per Minute', category: 'server', type: 'number', step: 1, min: 0, description: 'Maximum chat messages allowed per minute' },
  { key: 'bAllowClientMod', label: 'Allow Client Mod', category: 'server', type: 'boolean', description: 'Allow players to connect with client-side mods' },
  { key: 'bIsStartLocationSelectByMap', label: 'Is Start Location Select By Map', category: 'server', type: 'boolean', description: 'Allow players to select their starting location on the map' },
  { key: 'bInvisibleOtherGuildBaseCampAreaFX', label: 'Invisible Other Guild Base Camp Area FX', category: 'server', type: 'boolean', description: 'Hide the area effects of other guilds base camps' },
  { key: 'bIsUseBackupSaveData', label: 'Is Use Backup Save Data', category: 'server', type: 'boolean', description: 'Whether to use backup save data' },
  { key: 'LogFormatType', label: 'Log Format Type', category: 'server', type: 'select', options: ['Text', 'Json'], description: 'Format of the server log files' },
  { key: 'ServerReplicatePawnCullDistance', label: 'Server Replicate Pawn Cull Distance', category: 'server', type: 'number', step: 0.5, min: 0, description: 'Distance at which pawns are culled from replication' },

  // Advanced
  { key: 'RESTAPIEnabled', label: 'RESTAPI Enabled', category: 'advanced', type: 'boolean', description: 'Enable the REST API for server management' },
  { key: 'RESTAPIPort', label: 'RESTAPI Port', category: 'advanced', type: 'number', step: 1, min: 0, description: 'Port used for the REST API' },
  { key: 'RCONEnabled', label: 'RCON Enabled', category: 'advanced', type: 'boolean', description: 'Enable RCON for remote server management' },
  { key: 'RCONPort', label: 'RCON Port', category: 'advanced', type: 'number', step: 1, min: 0, description: 'Port used for RCON' },
  { key: 'BanListURL', label: 'Ban List URL', category: 'advanced', type: 'text', description: 'URL to fetch the ban list from' },
  { key: 'CrossplayPlatforms', label: 'Crossplay Platforms', category: 'advanced', type: 'text', description: 'Platforms allowed for crossplay (Steam,Xbox,PS5,Mac)' },
  { key: 'bEnableFastTravel', label: 'Enable Fast Travel', category: 'advanced', type: 'boolean', description: 'Enable fast travel across the map' },
  { key: 'bEnableFastTravelOnlyBaseCamp', label: 'Enable Fast Travel Only Base Camp', category: 'advanced', type: 'boolean', description: 'Restrict fast travel to only base camps' },
  { key: 'bEnableVoiceChat', label: 'Enable Voice Chat', category: 'advanced', type: 'boolean', description: 'Enable in-game voice chat' },
  { key: 'VoiceChatMaxVolumeDistance', label: 'Voice Chat Max Volume Distance', category: 'advanced', type: 'number', step: 1, min: 0, description: 'Maximum distance for full volume voice chat' },
  { key: 'VoiceChatZeroVolumeDistance', label: 'Voice Chat Zero Volume Distance', category: 'advanced', type: 'number', step: 1, min: 0, description: 'Distance at which voice chat drops to zero volume' },
  { key: 'DenyTechnologyList', label: 'Deny Technology List', category: 'advanced', type: 'text', description: 'Comma-separated list of technologies to disable' }
];

module.exports = { SETTINGS_SCHEMA, CATEGORIES };
